version: '3.9'
services:
  cloudflare-ddns:
    image: cloudflare-ddns-manager:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ASSET_VERSION=${ASSET_VERSION:-1.0.0}
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    restart: unless-stopped
